/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package casino.ui;

/**
 *
 * @author PRECIOUS
 */
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.*;
import java.util.logging.Level;
import java.util.logging.Logger;
public class GameMenu extends javax.swing.JFrame {
    Connection con;
    Statement st;
    String cs;
    
    String user;
    String password;
    
    String query;
    ResultSet rs;

    // For navigation
    private ResultSet navRs = null;
    private Statement navSt = null;
    private Connection navCon = null;


    /**
     * Creates new form GameMenu
     */
    public GameMenu() {
        initComponents();
        con=null;
        st=null;
        cs="jdbc:mysql://localhost:3306/casino_db";
        user="root";
        password="";
        setTitle("Manage Games");
        
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblGameName = new javax.swing.JLabel();
        lblMinbet = new javax.swing.JLabel();
        lblMaxBet = new javax.swing.JLabel();
        BtnNext = new javax.swing.JButton();
        btnAddGame = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        txtGamename = new javax.swing.JTextField();
        txtMinbet = new javax.swing.JTextField();
        txtMaxbet = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(102, 255, 51));
        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/icons8-rolling-dice-48.png"))); // NOI18N
        jLabel1.setText("Games");

        lblGameName.setText("Game    🎰");

        lblMinbet.setText("Min bet");

        lblMaxBet.setText("Max bet");

        BtnNext.setText("Next");
        BtnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNextActionPerformed(evt);
            }
        });

        btnAddGame.setText("➕ Add ");
        btnAddGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGameActionPerformed(evt);
            }
        });

        btnUpdate.setText("✏️ Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 0, 0));
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblGameName, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(lblMinbet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblMaxBet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtGamename)
                                    .addComponent(txtMinbet)
                                    .addComponent(txtMaxbet, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddGame)
                                .addGap(87, 87, 87)
                                .addComponent(btnUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnNext)))))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnBack))
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGamename, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(lblGameName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMinbet, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(lblMinbet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaxBet, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaxbet, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnNext)
                    .addComponent(btnAddGame)
                    .addComponent(btnUpdate))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String Gamename = txtGamename.getText();
        String minBet = txtMinbet.getText();
        String maxBet = txtMaxbet.getText();
        if(Gamename.equals("")){
            JOptionPane.showMessageDialog(this, "Enter the game name");
            txtGamename.requestFocus();
            return;
        }
        if(minBet.equals("")){
            JOptionPane.showMessageDialog(this, "Enter the game min bet");
            txtMinbet.requestFocus();
            return;
        }
        if(maxBet.equals("")){
            JOptionPane.showMessageDialog(this, "Enter the game max bet");
            txtMaxbet.requestFocus();
            return;
        }
        java.sql.PreparedStatement pstmt = null;
        try{
            Class.forName("com.mysql.jdbc.Driver");//registering driver
            con=DriverManager.getConnection(cs, user, password);
            query = "UPDATE games SET min_bet=?, max_bet=? WHERE game_name=?";
            pstmt = con.prepareStatement(query);
            pstmt.setString(1, minBet);
            pstmt.setString(2, maxBet);
            pstmt.setString(3, Gamename);
            int updated = pstmt.executeUpdate();
            if(updated > 0) {
                JOptionPane.showMessageDialog(this, "Record updated");
                txtGamename.setText("");
                txtMinbet.setText("");
                txtMaxbet.setText("");
                txtGamename.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "No record found to update.");
            }
        }
        catch(SQLException | ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
        finally{
            try{
                if(pstmt!=null) pstmt.close();
                if(con!=null) con.close();
            }
            catch(SQLException ex) {}
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAddGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGameActionPerformed
        String Gamename = txtGamename.getText();
        String minBet = txtMinbet.getText();
        String maxBet = txtMaxbet.getText();
        if(Gamename.equals("")){
        JOptionPane.showMessageDialog(this, "Enter the game name");
        txtGamename.requestFocus();
        return;}
        if(minBet.equals("")){
        JOptionPane.showMessageDialog(this, "Enter the game min bet");
        txtMinbet.requestFocus();
        return;}
        if(maxBet.equals("")){
        JOptionPane.showMessageDialog(this, "Enter the game max bet");
        txtMaxbet.requestFocus();
        return;
        }
        try{
            Class.forName("com.mysql.jdbc.Driver");//registering driver
            con=DriverManager.getConnection(cs, user, password);
            st=con.createStatement();
            query="INSERT INTO games(game_name, min_bet, max_bet)VALUES('"+Gamename+"','"+minBet+"','"+maxBet+"')";
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"record saved");
            txtGamename.setText("");
            txtMinbet.setText("");
            txtMaxbet.setText("");
            txtGamename.requestFocus();
        }
        catch(SQLException | ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
        finally{
            try{
                if(st!=null) st.close();
                if(con!=null) con.close();
            }
            catch(SQLException ex) {}
        }
        
    }//GEN-LAST:event_btnAddGameActionPerformed

    private void BtnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNextActionPerformed
        try {
            if (navRs == null) {
                // First time: initialize navigation ResultSet
                Class.forName("com.mysql.jdbc.Driver");
                navCon = DriverManager.getConnection(cs, user, password);
                navSt = navCon.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                navRs = navSt.executeQuery("SELECT game_name, min_bet, max_bet FROM games ORDER BY game_id");
                if (!navRs.next()) {
                    JOptionPane.showMessageDialog(this, "No records found.");
                    return;
                }
            } else {
                if (!navRs.next()) {
                    JOptionPane.showMessageDialog(this, "No more records.");
                    navRs.afterLast();
                    return;
                }
            }
            txtGamename.setText(navRs.getString("game_name"));
            txtMinbet.setText(navRs.getString("min_bet"));
            txtMaxbet.setText(navRs.getString("max_bet"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GameMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnNextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       MainDashboard.MainDashboardMain();
       this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

   
    public static void GameMain() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnNext;
    private javax.swing.JButton btnAddGame;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblGameName;
    private javax.swing.JLabel lblMaxBet;
    private javax.swing.JLabel lblMinbet;
    private javax.swing.JTextField txtGamename;
    private javax.swing.JTextField txtMaxbet;
    private javax.swing.JTextField txtMinbet;
    // End of variables declaration//GEN-END:variables
}
